# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(480, 60, 151, 111))
        self.btn_start.setObjectName("btn_start")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(650, 60, 161, 111))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 64, 15))
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(20, 90, 121, 41))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(180, 90, 121, 41))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(120, 186, 141, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 216, 141, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 64, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 220, 64, 15))
        self.label_4.setObjectName("label_4")
        self.textEdit_info = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_info.setGeometry(QtCore.QRect(630, 320, 301, 281))
        self.textEdit_info.setObjectName("textEdit_info")
        self.lbl_stat = QtWidgets.QLabel(self.centralwidget)
        self.lbl_stat.setGeometry(QtCore.QRect(490, 15, 281, 21))
        self.lbl_stat.setObjectName("lbl_stat")
        self.lbl_today = QtWidgets.QLabel(self.centralwidget)
        self.lbl_today.setGeometry(QtCore.QRect(50, 20, 71, 21))
        self.lbl_today.setObjectName("lbl_today")
        self.lbl_prierd = QtWidgets.QLabel(self.centralwidget)
        self.lbl_prierd.setGeometry(QtCore.QRect(340, 92, 56, 31))
        self.lbl_prierd.setObjectName("lbl_prierd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 301, 21))
        self.label_5.setObjectName("label_5")
        self.rb_2y = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_2y.setGeometry(QtCore.QRect(40, 150, 51, 19))
        self.rb_2y.setObjectName("rb_2y")
        self.rb_1y = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1y.setGeometry(QtCore.QRect(90, 150, 51, 19))
        self.rb_1y.setObjectName("rb_1y")
        self.rb_6m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_6m.setGeometry(QtCore.QRect(140, 150, 51, 19))
        self.rb_6m.setObjectName("rb_6m")
        self.rb_1m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1m.setGeometry(QtCore.QRect(240, 150, 51, 19))
        self.rb_1m.setChecked(True)
        self.rb_1m.setObjectName("rb_1m")
        self.rb_3m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_3m.setGeometry(QtCore.QRect(190, 150, 51, 19))
        self.rb_3m.setObjectName("rb_3m")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 190, 201, 41))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_start.clicked.connect(MainWindow.aStart)
        self.btn_cancel.clicked.connect(MainWindow.cancel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_cancel.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "시작날짜"))
        self.label_2.setText(_translate("MainWindow", "마지막날짜"))
        self.label_3.setText(_translate("MainWindow", "대상종목:"))
        self.label_4.setText(_translate("MainWindow", "비교종목:"))
        self.lbl_stat.setText(_translate("MainWindow", "state"))
        self.lbl_today.setText(_translate("MainWindow", "TodayDate"))
        self.lbl_prierd.setText(_translate("MainWindow", "0 Day"))
        self.label_5.setText(_translate("MainWindow", "ex) 애플: APPL   , 삼성: 005930.KS"))
        self.rb_2y.setText(_translate("MainWindow", "2y"))
        self.rb_1y.setText(_translate("MainWindow", "1y"))
        self.rb_6m.setText(_translate("MainWindow", "6m"))
        self.rb_1m.setText(_translate("MainWindow", "1m"))
        self.rb_3m.setText(_translate("MainWindow", "3m"))
        self.label_6.setText(_translate("MainWindow", "help"))
        self.menu.setTitle(_translate("MainWindow", "비교분석"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
