# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StockAnlyst(object):
    def setupUi(self, StockAnlyst):
        StockAnlyst.setObjectName("StockAnlyst")
        StockAnlyst.resize(1000, 750)
        font = QtGui.QFont()
        font.setFamily("HY그래픽M")
        StockAnlyst.setFont(font)
        self.centralwidget = QtWidgets.QWidget(StockAnlyst)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(480, 60, 151, 111))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(650, 60, 161, 111))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 43, 64, 15))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(20, 73, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 43, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(180, 73, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(100, 169, 141, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 199, 141, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 173, 64, 15))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 203, 64, 15))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_info = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_info.setGeometry(QtCore.QRect(570, 280, 301, 321))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.textEdit_info.setFont(font)
        self.textEdit_info.setObjectName("textEdit_info")
        self.lbl_prierd = QtWidgets.QLabel(self.centralwidget)
        self.lbl_prierd.setGeometry(QtCore.QRect(340, 75, 56, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.lbl_prierd.setFont(font)
        self.lbl_prierd.setObjectName("lbl_prierd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 233, 301, 21))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.rb_2y = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_2y.setGeometry(QtCore.QRect(40, 133, 51, 19))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.rb_2y.setFont(font)
        self.rb_2y.setObjectName("rb_2y")
        self.rb_1y = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1y.setGeometry(QtCore.QRect(90, 133, 51, 19))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.rb_1y.setFont(font)
        self.rb_1y.setObjectName("rb_1y")
        self.rb_6m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_6m.setGeometry(QtCore.QRect(140, 133, 51, 19))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.rb_6m.setFont(font)
        self.rb_6m.setObjectName("rb_6m")
        self.rb_1m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1m.setGeometry(QtCore.QRect(240, 133, 51, 19))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.rb_1m.setFont(font)
        self.rb_1m.setChecked(True)
        self.rb_1m.setObjectName("rb_1m")
        self.rb_3m = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_3m.setGeometry(QtCore.QRect(190, 133, 51, 19))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.rb_3m.setFont(font)
        self.rb_3m.setObjectName("rb_3m")
        self.btn_more1 = QtWidgets.QToolButton(self.centralwidget)
        self.btn_more1.setGeometry(QtCore.QRect(250, 168, 27, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.btn_more1.setFont(font)
        self.btn_more1.setObjectName("btn_more1")
        self.btn_more2 = QtWidgets.QToolButton(self.centralwidget)
        self.btn_more2.setGeometry(QtCore.QRect(250, 200, 27, 18))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        self.btn_more2.setFont(font)
        self.btn_more2.setObjectName("btn_more2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(147, 85, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(670, 610, 93, 41))
        self.btn_save.setObjectName("btn_save")
        self.btn_resultClear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_resultClear.setGeometry(QtCore.QRect(770, 610, 93, 41))
        self.btn_resultClear.setObjectName("btn_resultClear")
        self.lbl_name1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name1.setGeometry(QtCore.QRect(310, 170, 151, 20))
        self.lbl_name1.setObjectName("lbl_name1")
        self.lbl_name2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name2.setGeometry(QtCore.QRect(310, 200, 151, 20))
        self.lbl_name2.setObjectName("lbl_name2")
        StockAnlyst.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockAnlyst)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        StockAnlyst.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StockAnlyst)
        self.statusbar.setObjectName("statusbar")
        StockAnlyst.setStatusBar(self.statusbar)

        self.retranslateUi(StockAnlyst)
        self.btn_start.clicked.connect(StockAnlyst.aStart)
        self.btn_cancel.clicked.connect(StockAnlyst.cancel)
        QtCore.QMetaObject.connectSlotsByName(StockAnlyst)

    def retranslateUi(self, StockAnlyst):
        _translate = QtCore.QCoreApplication.translate
        StockAnlyst.setWindowTitle(_translate("StockAnlyst", "MainWindow"))
        self.btn_start.setText(_translate("StockAnlyst", "Start"))
        self.btn_cancel.setText(_translate("StockAnlyst", "Clear"))
        self.label.setText(_translate("StockAnlyst", "시작날짜"))
        self.label_2.setText(_translate("StockAnlyst", "마지막날짜"))
        self.label_3.setText(_translate("StockAnlyst", "대상종목:"))
        self.label_4.setText(_translate("StockAnlyst", "비교종목:"))
        self.lbl_prierd.setText(_translate("StockAnlyst", "0 Day"))
        self.label_5.setText(_translate("StockAnlyst", "ex) 애플: APPL, 삼성: 005930.KS"))
        self.rb_2y.setText(_translate("StockAnlyst", "2Y"))
        self.rb_1y.setText(_translate("StockAnlyst", "1Y"))
        self.rb_6m.setText(_translate("StockAnlyst", "6m"))
        self.rb_1m.setText(_translate("StockAnlyst", "1m"))
        self.rb_3m.setText(_translate("StockAnlyst", "3m"))
        self.btn_more1.setText(_translate("StockAnlyst", "..."))
        self.btn_more2.setText(_translate("StockAnlyst", "..."))
        self.label_6.setText(_translate("StockAnlyst", "~"))
        self.btn_save.setText(_translate("StockAnlyst", "Save"))
        self.btn_resultClear.setText(_translate("StockAnlyst", "Clear"))
        self.lbl_name1.setText(_translate("StockAnlyst", ".."))
        self.lbl_name2.setText(_translate("StockAnlyst", ".."))


